# Generated by Django 4.1.2 on 2022-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.TextField()),
                ('info', models.CharField(max_length=200)),
                ('facts', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=5)),
                ('allergy', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=30)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
